export const UPDATE_STOCK_NAME = 'UPDATE_STOCK_NAME';
export const UPDATE_STOCK_PRICE = 'UPDATE_STOCK_PRICE';
export const UPDATE_STOCK_DESCRIPTION = 'UPDATE_STOCK_DESCRIPTION';
export const UPDATE_STOCK_CATEGORIES = 'UPDATE_STOCK_CATEGORIES';
export const UPDATE_EVENT = 'UPDATE_EVENT';
